'\" t
.\"     Title: sssd-ldap
.\"    Author: The SSSD upstream - http://fedorahosted.org/sssd
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 01/16/2015
.\"    Manual: File Formats and Conventions
.\"    Source: SSSD
.\"  Language: English
.\"
.TH "SSSD\-LDAP" "5" "01/16/2015" "SSSD" "File Formats and Conventions"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
sssd-ldap \- the configuration file for SSSD
.SH "DESCRIPTION"
.PP
This manual page describes the configuration of LDAP domains for
\fBsssd\fR(8)\&. Refer to the
\(lqFILE FORMAT\(rq
section of the
\fBsssd.conf\fR(5)
manual page for detailed syntax information\&.
.PP
You can configure SSSD to use more than one LDAP domain\&.
.PP
LDAP back end supports id, auth, access and chpass providers\&. If you want to authenticate against an LDAP server either TLS/SSL or LDAPS is required\&.
\fBsssd\fR\fIdoes not\fR
support authentication over an unencrypted channel\&. If the LDAP server is used only as an identity provider, an encrypted channel is not needed\&. Please refer to
\(lqldap_access_filter\(rq
config option for more information about using LDAP as an access provider\&.
.SH "CONFIGURATION OPTIONS"
.PP
All of the common configuration options that apply to SSSD domains also apply to LDAP domains\&. Refer to the
\(lqDOMAIN SECTIONS\(rq
section of the
\fBsssd.conf\fR(5)
manual page for full details\&.
.PP
ldap_uri, ldap_backup_uri (string)
.RS 4
Specifies the comma\-separated list of URIs of the LDAP servers to which SSSD should connect in the order of preference\&. Refer to the
\(lqFAILOVER\(rq
section for more information on failover and server redundancy\&. If neither option is specified, service discovery is enabled\&. For more information, refer to the
\(lqSERVICE DISCOVERY\(rq
section\&.
.sp
The format of the URI must match the format defined in RFC 2732:
.sp
ldap[s]://<host>[:port]
.sp
For explicit IPv6 addresses, <host> must be enclosed in brackets []
.sp
example: ldap://[fc00::126:25]:389
.RE
.PP
ldap_chpass_uri, ldap_chpass_backup_uri (string)
.RS 4
Specifies the comma\-separated list of URIs of the LDAP servers to which SSSD should connect in the order of preference to change the password of a user\&. Refer to the
\(lqFAILOVER\(rq
section for more information on failover and server redundancy\&.
.sp
To enable service discovery ldap_chpass_dns_service_name must be set\&.
.sp
Default: empty, i\&.e\&. ldap_uri is used\&.
.RE
.PP
ldap_search_base (string)
.RS 4
The default base DN to use for performing LDAP user operations\&.
.sp
Starting with SSSD 1\&.7\&.0, SSSD supports multiple search bases using the syntax:
.sp
search_base[?scope?[filter][?search_base?scope?[filter]]*]
.sp
The scope can be one of "base", "onelevel" or "subtree"\&.
.sp
The filter must be a valid LDAP search filter as specified by http://www\&.ietf\&.org/rfc/rfc2254\&.txt
.sp
Examples:
.sp
ldap_search_base = dc=example,dc=com (which is equivalent to) ldap_search_base = dc=example,dc=com?subtree?
.sp
ldap_search_base = cn=host_specific,dc=example,dc=com?subtree?(host=thishost)?dc=example\&.com?subtree?
.sp
Note: It is unsupported to have multiple search bases which reference identically\-named objects (for example, groups with the same name in two different search bases)\&. This will lead to unpredictable behavior on client machines\&.
.sp
Default: If not set, the value of the defaultNamingContext or namingContexts attribute from the RootDSE of the LDAP server is used\&. If defaultNamingContext does not exist or has an empty value namingContexts is used\&. The namingContexts attribute must have a single value with the DN of the search base of the LDAP server to make this work\&. Multiple values are are not supported\&.
.RE
.PP
ldap_schema (string)
.RS 4
Specifies the Schema Type in use on the target LDAP server\&. Depending on the selected schema, the default attribute names retrieved from the servers may vary\&. The way that some attributes are handled may also differ\&.
.sp
Four schema types are currently supported:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
rfc2307
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
rfc2307bis
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
IPA
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
AD
.RE
.sp
The main difference between these schema types is how group memberships are recorded in the server\&. With rfc2307, group members are listed by name in the
\fImemberUid\fR
attribute\&. With rfc2307bis and IPA, group members are listed by DN and stored in the
\fImember\fR
attribute\&. The AD schema type sets the attributes to correspond with Active Directory 2008r2 values\&.
.sp
Default: rfc2307
.RE
.PP
ldap_default_bind_dn (string)
.RS 4
The default bind DN to use for performing LDAP operations\&.
.RE
.PP
ldap_default_authtok_type (string)
.RS 4
The type of the authentication token of the default bind DN\&.
.sp
The two mechanisms currently supported are:
.sp
password
.sp
obfuscated_password
.sp
Default: password
.RE
.PP
ldap_default_authtok (string)
.RS 4
The authentication token of the default bind DN\&. Only clear text passwords are currently supported\&.
.RE
.PP
ldap_user_object_class (string)
.RS 4
The object class of a user entry in LDAP\&.
.sp
Default: posixAccount
.RE
.PP
ldap_user_name (string)
.RS 4
The LDAP attribute that corresponds to the user\*(Aqs login name\&.
.sp
Default: uid
.RE
.PP
ldap_user_uid_number (string)
.RS 4
The LDAP attribute that corresponds to the user\*(Aqs id\&.
.sp
Default: uidNumber
.RE
.PP
ldap_user_gid_number (string)
.RS 4
The LDAP attribute that corresponds to the user\*(Aqs primary group id\&.
.sp
Default: gidNumber
.RE
.PP
ldap_user_gecos (string)
.RS 4
The LDAP attribute that corresponds to the user\*(Aqs gecos field\&.
.sp
Default: gecos
.RE
.PP
ldap_user_home_directory (string)
.RS 4
The LDAP attribute that contains the name of the user\*(Aqs home directory\&.
.sp
Default: homeDirectory
.RE
.PP
ldap_user_shell (string)
.RS 4
The LDAP attribute that contains the path to the user\*(Aqs default shell\&.
.sp
Default: loginShell
.RE
.PP
ldap_user_objectsid (string)
.RS 4
The LDAP attribute that contains the objectSID of an LDAP user object\&. This is usually only necessary for ActiveDirectory servers\&.
.sp
Default: objectSid for ActiveDirectory, not set for other servers\&.
.RE
.PP
ldap_user_modify_timestamp (string)
.RS 4
The LDAP attribute that contains timestamp of the last modification of the parent object\&.
.sp
Default: modifyTimestamp
.RE
.PP
ldap_user_shadow_last_change (string)
.RS 4
When using ldap_pwd_policy=shadow, this parameter contains the name of an LDAP attribute corresponding to its
\fBshadow\fR(5)
counterpart (date of the last password change)\&.
.sp
Default: shadowLastChange
.RE
.PP
ldap_user_shadow_min (string)
.RS 4
When using ldap_pwd_policy=shadow, this parameter contains the name of an LDAP attribute corresponding to its
\fBshadow\fR(5)
counterpart (minimum password age)\&.
.sp
Default: shadowMin
.RE
.PP
ldap_user_shadow_max (string)
.RS 4
When using ldap_pwd_policy=shadow, this parameter contains the name of an LDAP attribute corresponding to its
\fBshadow\fR(5)
counterpart (maximum password age)\&.
.sp
Default: shadowMax
.RE
.PP
ldap_user_shadow_warning (string)
.RS 4
When using ldap_pwd_policy=shadow, this parameter contains the name of an LDAP attribute corresponding to its
\fBshadow\fR(5)
counterpart (password warning period)\&.
.sp
Default: shadowWarning
.RE
.PP
ldap_user_shadow_inactive (string)
.RS 4
When using ldap_pwd_policy=shadow, this parameter contains the name of an LDAP attribute corresponding to its
\fBshadow\fR(5)
counterpart (password inactivity period)\&.
.sp
Default: shadowInactive
.RE
.PP
ldap_user_shadow_expire (string)
.RS 4
When using ldap_pwd_policy=shadow or ldap_account_expire_policy=shadow, this parameter contains the name of an LDAP attribute corresponding to its
\fBshadow\fR(5)
counterpart (account expiration date)\&.
.sp
Default: shadowExpire
.RE
.PP
ldap_user_krb_last_pwd_change (string)
.RS 4
When using ldap_pwd_policy=mit_kerberos, this parameter contains the name of an LDAP attribute storing the date and time of last password change in kerberos\&.
.sp
Default: krbLastPwdChange
.RE
.PP
ldap_user_krb_password_expiration (string)
.RS 4
When using ldap_pwd_policy=mit_kerberos, this parameter contains the name of an LDAP attribute storing the date and time when current password expires\&.
.sp
Default: krbPasswordExpiration
.RE
.PP
ldap_user_ad_account_expires (string)
.RS 4
When using ldap_account_expire_policy=ad, this parameter contains the name of an LDAP attribute storing the expiration time of the account\&.
.sp
Default: accountExpires
.RE
.PP
ldap_user_ad_user_account_control (string)
.RS 4
When using ldap_account_expire_policy=ad, this parameter contains the name of an LDAP attribute storing the user account control bit field\&.
.sp
Default: userAccountControl
.RE
.PP
ldap_ns_account_lock (string)
.RS 4
When using ldap_account_expire_policy=rhds or equivalent, this parameter determines if access is allowed or not\&.
.sp
Default: nsAccountLock
.RE
.PP
ldap_user_nds_login_disabled (string)
.RS 4
When using ldap_account_expire_policy=nds, this attribute determines if access is allowed or not\&.
.sp
Default: loginDisabled
.RE
.PP
ldap_user_nds_login_expiration_time (string)
.RS 4
When using ldap_account_expire_policy=nds, this attribute determines until which date access is granted\&.
.sp
Default: loginDisabled
.RE
.PP
ldap_user_nds_login_allowed_time_map (string)
.RS 4
When using ldap_account_expire_policy=nds, this attribute determines the hours of a day in a week when access is granted\&.
.sp
Default: loginAllowedTimeMap
.RE
.PP
ldap_user_principal (string)
.RS 4
The LDAP attribute that contains the user\*(Aqs Kerberos User Principal Name (UPN)\&.
.sp
Default: krbPrincipalName
.RE
.PP
ldap_user_extra_attrs (string)
.RS 4
Comma\-separated list of LDAP attributes that SSSD would fetch along with the usual set of user attributes\&.
.sp
The list can either contain LDAP attribute names only, or colon\-separated tuples of SSSD cache attribute name and LDAP attribute name\&. In case only LDAP attribute name is specified, the attribute is saved to the cache verbatim\&. Using a custom SSSD attribute name might be required by environments that configure several SSSD domains with different LDAP schemas\&.
.sp
Please note that several attribute names are reserved by SSSD, notably the
\(lqname\(rq
attribute\&. SSSD would report an error if any of the reserved attribute names is used as an extra attribute name\&.
.sp
Examples:
.sp
ldap_user_extra_attrs = telephoneNumber
.sp
Save the
\(lqtelephoneNumber\(rq
attribute from LDAP as
\(lqtelephoneNumber\(rq
to the cache\&.
.sp
ldap_user_extra_attrs = phone:telephoneNumber
.sp
Save the
\(lqtelephoneNumber\(rq
attribute from LDAP as
\(lqphone\(rq
to the cache\&.
.sp
Default: not set
.RE
.PP
ldap_user_ssh_public_key (string)
.RS 4
The LDAP attribute that contains the user\*(Aqs SSH public keys\&.
.RE
.PP
ldap_force_upper_case_realm (boolean)
.RS 4
Some directory servers, for example Active Directory, might deliver the realm part of the UPN in lower case, which might cause the authentication to fail\&. Set this option to a non\-zero value if you want to use an upper\-case realm\&.
.sp
Default: false
.RE
.PP
ldap_enumeration_refresh_timeout (integer)
.RS 4
Specifies how many seconds SSSD has to wait before refreshing its cache of enumerated records\&.
.sp
Default: 300
.RE
.PP
ldap_purge_cache_timeout (integer)
.RS 4
Determine how often to check the cache for inactive entries (such as groups with no members and users who have never logged in) and remove them to save space\&.
.sp
Setting this option to zero will disable the cache cleanup operation\&.
.sp
Default: 10800 (12 hours)
.RE
.PP
ldap_user_fullname (string)
.RS 4
The LDAP attribute that corresponds to the user\*(Aqs full name\&.
.sp
Default: cn
.RE
.PP
ldap_user_member_of (string)
.RS 4
The LDAP attribute that lists the user\*(Aqs group memberships\&.
.sp
Default: memberOf
.RE
.PP
ldap_user_authorized_service (string)
.RS 4
If access_provider=ldap and ldap_access_order=authorized_service, SSSD will use the presence of the authorizedService attribute in the user\*(Aqs LDAP entry to determine access privilege\&.
.sp
An explicit deny (!svc) is resolved first\&. Second, SSSD searches for explicit allow (svc) and finally for allow_all (*)\&.
.sp
Please note that the ldap_access_order configuration option
\fImust\fR
include
\(lqauthorized_service\(rq
in order for the ldap_user_authorized_service option to work\&.
.sp
Default: authorizedService
.RE
.PP
ldap_user_authorized_host (string)
.RS 4
If access_provider=ldap and ldap_access_order=host, SSSD will use the presence of the host attribute in the user\*(Aqs LDAP entry to determine access privilege\&.
.sp
An explicit deny (!host) is resolved first\&. Second, SSSD searches for explicit allow (host) and finally for allow_all (*)\&.
.sp
Please note that the ldap_access_order configuration option
\fImust\fR
include
\(lqhost\(rq
in order for the ldap_user_authorized_host option to work\&.
.sp
Default: host
.RE
.PP
ldap_group_object_class (string)
.RS 4
The object class of a group entry in LDAP\&.
.sp
Default: posixGroup
.RE
.PP
ldap_group_name (string)
.RS 4
The LDAP attribute that corresponds to the group name\&.
.sp
Default: cn
.RE
.PP
ldap_group_gid_number (string)
.RS 4
The LDAP attribute that corresponds to the group\*(Aqs id\&.
.sp
Default: gidNumber
.RE
.PP
ldap_group_member (string)
.RS 4
The LDAP attribute that contains the names of the group\*(Aqs members\&.
.sp
Default: memberuid (rfc2307) / member (rfc2307bis)
.RE
.PP
ldap_group_objectsid (string)
.RS 4
The LDAP attribute that contains the objectSID of an LDAP group object\&. This is usually only necessary for ActiveDirectory servers\&.
.sp
Default: objectSid for ActiveDirectory, not set for other servers\&.
.RE
.PP
ldap_group_modify_timestamp (string)
.RS 4
The LDAP attribute that contains timestamp of the last modification of the parent object\&.
.sp
Default: modifyTimestamp
.RE
.PP
ldap_group_type (integer)
.RS 4
The LDAP attribute that contains an integer value indicating the type of the group and maybe other flags\&.
.sp
This attribute is currently only used by the AD provider to determine if a group is a domain local groups and has to be filtered out for trusted domains\&.
.sp
Default: groupType in the AD provider, othewise not set
.RE
.PP
ldap_group_nesting_level (integer)
.RS 4
If ldap_schema is set to a schema format that supports nested groups (e\&.g\&. RFC2307bis), then this option controls how many levels of nesting SSSD will follow\&. This option has no effect on the RFC2307 schema\&.
.sp
Note: This option specifies the guaranteed level of nested groups to be processed for any lookup\&. However, nested groups beyond this limit
\fImay be\fR
returned if previous lookups already resolved the deeper nesting levels\&. Also, subsequent lookups for other groups may enlarge the result set for original lookup if re\-queried\&.
.sp
If ldap_group_nesting_level is set to 0 then no nested groups are processed at all\&. However, when connected to Active\-Directory Server 2008 and later it is furthermore required to disable usage of Token\-Groups by setting ldap_use_tokengroups to false\&.
.sp
Default: 2
.RE
.PP
ldap_groups_use_matching_rule_in_chain
.RS 4
This option tells SSSD to take advantage of an Active Directory\-specific feature which may speed up group lookup operations on deployments with complex or deep nested groups\&.
.sp
In most common cases, it is best to leave this option disabled\&. It generally only provides a performance increase on very complex nestings\&.
.sp
If this option is enabled, SSSD will use it if it detects that the server supports it during initial connection\&. So "True" here essentially means "auto\-detect"\&.
.sp
Note: This feature is currently known to work only with Active Directory 2008 R1 and later\&. See
\m[blue]\fBMSDN(TM) documentation\fR\m[]\&\s-2\u[1]\d\s+2
for more details\&.
.sp
Default: False
.RE
.PP
ldap_initgroups_use_matching_rule_in_chain
.RS 4
This option tells SSSD to take advantage of an Active Directory\-specific feature which might speed up initgroups operations (most notably when dealing with complex or deep nested groups)\&.
.sp
If this option is enabled, SSSD will use it if it detects that the server supports it during initial connection\&. So "True" here essentially means "auto\-detect"\&.
.sp
Note: This feature is currently known to work only with Active Directory 2008 R1 and later\&. See
\m[blue]\fBMSDN(TM) documentation\fR\m[]\&\s-2\u[1]\d\s+2
for more details\&.
.sp
Default: False
.RE
.PP
ldap_use_tokengroups
.RS 4
This options enables or disables use of Token\-Groups attribute when performing initgroup for users from Active Directory Server 2008 and later\&.
.sp
Default: True
.RE
.PP
ldap_netgroup_object_class (string)
.RS 4
The object class of a netgroup entry in LDAP\&.
.sp
In IPA provider, ipa_netgroup_object_class should be used instead\&.
.sp
Default: nisNetgroup
.RE
.PP
ldap_netgroup_name (string)
.RS 4
The LDAP attribute that corresponds to the netgroup name\&.
.sp
In IPA provider, ipa_netgroup_name should be used instead\&.
.sp
Default: cn
.RE
.PP
ldap_netgroup_member (string)
.RS 4
The LDAP attribute that contains the names of the netgroup\*(Aqs members\&.
.sp
In IPA provider, ipa_netgroup_member should be used instead\&.
.sp
Default: memberNisNetgroup
.RE
.PP
ldap_netgroup_triple (string)
.RS 4
The LDAP attribute that contains the (host, user, domain) netgroup triples\&.
.sp
This option is not available in IPA provider\&.
.sp
Default: nisNetgroupTriple
.RE
.PP
ldap_netgroup_modify_timestamp (string)
.RS 4
The LDAP attribute that contains timestamp of the last modification of the parent object\&.
.sp
This option is not available in IPA provider\&.
.sp
Default: modifyTimestamp
.RE
.PP
ldap_service_object_class (string)
.RS 4
The object class of a service entry in LDAP\&.
.sp
Default: ipService
.RE
.PP
ldap_service_name (string)
.RS 4
The LDAP attribute that contains the name of service attributes and their aliases\&.
.sp
Default: cn
.RE
.PP
ldap_service_port (string)
.RS 4
The LDAP attribute that contains the port managed by this service\&.
.sp
Default: ipServicePort
.RE
.PP
ldap_service_proto (string)
.RS 4
The LDAP attribute that contains the protocols understood by this service\&.
.sp
Default: ipServiceProtocol
.RE
.PP
ldap_service_search_base (string)
.RS 4
An optional base DN, search scope and LDAP filter to restrict LDAP searches for this attribute type\&.
.sp
syntax:
.sp
.if n \{\
.RS 4
.\}
.nf
search_base[?scope?[filter][?search_base?scope?[filter]]*]
.fi
.if n \{\
.RE
.\}
.sp
The scope can be one of "base", "onelevel" or "subtree"\&. The filter must be a valid LDAP search filter as specified by http://www\&.ietf\&.org/rfc/rfc2254\&.txt
.sp
For examples of this syntax, please refer to the
\(lqldap_search_base\(rq
examples section\&.
.sp
Default: the value of
\fIldap_search_base\fR
.sp
Please note that specifying scope or filter is not supported for searches against an Active Directory Server that might yield a large number of results and trigger the Range Retrieval extension in the response\&.
.RE
.PP
ldap_search_timeout (integer)
.RS 4
Specifies the timeout (in seconds) that ldap searches are allowed to run before they are cancelled and cached results are returned (and offline mode is entered)
.sp
Note: this option is subject to change in future versions of the SSSD\&. It will likely be replaced at some point by a series of timeouts for specific lookup types\&.
.sp
Default: 6
.RE
.PP
ldap_enumeration_search_timeout (integer)
.RS 4
Specifies the timeout (in seconds) that ldap searches for user and group enumerations are allowed to run before they are cancelled and cached results are returned (and offline mode is entered)
.sp
Default: 60
.RE
.PP
ldap_network_timeout (integer)
.RS 4
Specifies the timeout (in seconds) after which the
\fBpoll\fR(2)/\fBselect\fR(2)
following a
\fBconnect\fR(2)
returns in case of no activity\&.
.sp
Default: 6
.RE
.PP
ldap_opt_timeout (integer)
.RS 4
Specifies a timeout (in seconds) after which calls to synchronous LDAP APIs will abort if no response is received\&. Also controls the timeout when communicating with the KDC in case of SASL bind\&.
.sp
Default: 6
.RE
.PP
ldap_connection_expire_timeout (integer)
.RS 4
Specifies a timeout (in seconds) that a connection to an LDAP server will be maintained\&. After this time, the connection will be re\-established\&. If used in parallel with SASL/GSSAPI, the sooner of the two values (this value vs\&. the TGT lifetime) will be used\&.
.sp
Default: 900 (15 minutes)
.RE
.PP
ldap_page_size (integer)
.RS 4
Specify the number of records to retrieve from LDAP in a single request\&. Some LDAP servers enforce a maximum limit per\-request\&.
.sp
Default: 1000
.RE
.PP
ldap_disable_paging (boolean)
.RS 4
Disable the LDAP paging control\&. This option should be used if the LDAP server reports that it supports the LDAP paging control in its RootDSE but it is not enabled or does not behave properly\&.
.sp
Example: OpenLDAP servers with the paging control module installed on the server but not enabled will report it in the RootDSE but be unable to use it\&.
.sp
Example: 389 DS has a bug where it can only support a one paging control at a time on a single connection\&. On busy clients, this can result in some requests being denied\&.
.sp
Default: False
.RE
.PP
ldap_disable_range_retrieval (boolean)
.RS 4
Disable Active Directory range retrieval\&.
.sp
Active Directory limits the number of members to be retrieved in a single lookup using the MaxValRange policy (which defaults to 1500 members)\&. If a group contains more members, the reply would include an AD\-specific range extension\&. This option disables parsing of the range extension, therefore large groups will appear as having no members\&.
.sp
Default: False
.RE
.PP
ldap_sasl_minssf (integer)
.RS 4
When communicating with an LDAP server using SASL, specify the minimum security level necessary to establish the connection\&. The values of this option are defined by OpenLDAP\&.
.sp
Default: Use the system default (usually specified by ldap\&.conf)
.RE
.PP
ldap_deref_threshold (integer)
.RS 4
Specify the number of group members that must be missing from the internal cache in order to trigger a dereference lookup\&. If less members are missing, they are looked up individually\&.
.sp
You can turn off dereference lookups completely by setting the value to 0\&.
.sp
A dereference lookup is a means of fetching all group members in a single LDAP call\&. Different LDAP servers may implement different dereference methods\&. The currently supported servers are 389/RHDS, OpenLDAP and Active Directory\&.
.sp
\fINote:\fR
If any of the search bases specifies a search filter, then the dereference lookup performance enhancement will be disabled regardless of this setting\&.
.sp
Default: 10
.RE
.PP
ldap_tls_reqcert (string)
.RS 4
Specifies what checks to perform on server certificates in a TLS session, if any\&. It can be specified as one of the following values:
.sp
\fInever\fR
= The client will not request or check any server certificate\&.
.sp
\fIallow\fR
= The server certificate is requested\&. If no certificate is provided, the session proceeds normally\&. If a bad certificate is provided, it will be ignored and the session proceeds normally\&.
.sp
\fItry\fR
= The server certificate is requested\&. If no certificate is provided, the session proceeds normally\&. If a bad certificate is provided, the session is immediately terminated\&.
.sp
\fIdemand\fR
= The server certificate is requested\&. If no certificate is provided, or a bad certificate is provided, the session is immediately terminated\&.
.sp
\fIhard\fR
= Same as
\(lqdemand\(rq
.sp
Default: hard
.RE
.PP
ldap_tls_cacert (string)
.RS 4
Specifies the file that contains certificates for all of the Certificate Authorities that
\fBsssd\fR
will recognize\&.
.sp
Default: use OpenLDAP defaults, typically in
/etc/openldap/ldap\&.conf
.RE
.PP
ldap_tls_cacertdir (string)
.RS 4
Specifies the path of a directory that contains Certificate Authority certificates in separate individual files\&. Typically the file names need to be the hash of the certificate followed by \*(Aq\&.0\*(Aq\&. If available,
\fBcacertdir_rehash\fR
can be used to create the correct names\&.
.sp
Default: use OpenLDAP defaults, typically in
/etc/openldap/ldap\&.conf
.RE
.PP
ldap_tls_cert (string)
.RS 4
Specifies the file that contains the certificate for the client\*(Aqs key\&.
.sp
Default: not set
.RE
.PP
ldap_tls_key (string)
.RS 4
Specifies the file that contains the client\*(Aqs key\&.
.sp
Default: not set
.RE
.PP
ldap_tls_cipher_suite (string)
.RS 4
Specifies acceptable cipher suites\&. Typically this is a colon sperated list\&. See
\fBldap.conf\fR(5)
for format\&.
.sp
Default: use OpenLDAP defaults, typically in
/etc/openldap/ldap\&.conf
.RE
.PP
ldap_id_use_start_tls (boolean)
.RS 4
Specifies that the id_provider connection must also use
tls
to protect the channel\&.
.sp
Default: false
.RE
.PP
ldap_id_mapping (boolean)
.RS 4
Specifies that SSSD should attempt to map user and group IDs from the ldap_user_objectsid and ldap_group_objectsid attributes instead of relying on ldap_user_uid_number and ldap_group_gid_number\&.
.sp
Currently this feature supports only ActiveDirectory objectSID mapping\&.
.sp
Default: false
.RE
.PP
ldap_min_id, ldap_max_id (interger)
.RS 4
In contrast to the SID based ID mapping which is used if ldap_id_mapping is set to true the allowed ID range for ldap_user_uid_number and ldap_group_gid_number is unbound\&. In a setup with sub/trusted\-domains this might lead to ID collisions\&. To avoid collisions ldap_min_id and ldap_max_id can be set to restrict the allowed range for the IDs which are read directly from the server\&. Sub\-domains can then pick other ranges to map IDs\&.
.sp
Default: not set (both options are set to 0)
.RE
.PP
ldap_sasl_mech (string)
.RS 4
Specify the SASL mechanism to use\&. Currently only GSSAPI is tested and supported\&.
.sp
Default: not set
.RE
.PP
ldap_sasl_authid (string)
.RS 4
Specify the SASL authorization id to use\&. When GSSAPI is used, this represents the Kerberos principal used for authentication to the directory\&. This option can either contain the full principal (for example host/myhost@EXAMPLE\&.COM) or just the principal name (for example host/myhost)\&.
.sp
Default: host/hostname@REALM
.RE
.PP
ldap_sasl_realm (string)
.RS 4
Specify the SASL realm to use\&. When not specified, this option defaults to the value of krb5_realm\&. If the ldap_sasl_authid contains the realm as well, this option is ignored\&.
.sp
Default: the value of krb5_realm\&.
.RE
.PP
ldap_sasl_canonicalize (boolean)
.RS 4
If set to true, the LDAP library would perform a reverse lookup to canonicalize the host name during a SASL bind\&.
.sp
Default: false;
.RE
.PP
ldap_krb5_keytab (string)
.RS 4
Specify the keytab to use when using SASL/GSSAPI\&.
.sp
Default: System keytab, normally
/etc/krb5\&.keytab
.RE
.PP
ldap_krb5_init_creds (boolean)
.RS 4
Specifies that the id_provider should init Kerberos credentials (TGT)\&. This action is performed only if SASL is used and the mechanism selected is GSSAPI\&.
.sp
Default: true
.RE
.PP
ldap_krb5_ticket_lifetime (integer)
.RS 4
Specifies the lifetime in seconds of the TGT if GSSAPI is used\&.
.sp
Default: 86400 (24 hours)
.RE
.PP
krb5_server, krb5_backup_server (string)
.RS 4
Specifies the comma\-separated list of IP addresses or hostnames of the Kerberos servers to which SSSD should connect in the order of preference\&. For more information on failover and server redundancy, see the
\(lqFAILOVER\(rq
section\&. An optional port number (preceded by a colon) may be appended to the addresses or hostnames\&. If empty, service discovery is enabled \- for more information, refer to the
\(lqSERVICE DISCOVERY\(rq
section\&.
.sp
When using service discovery for KDC or kpasswd servers, SSSD first searches for DNS entries that specify _udp as the protocol and falls back to _tcp if none are found\&.
.sp
This option was named
\(lqkrb5_kdcip\(rq
in earlier releases of SSSD\&. While the legacy name is recognized for the time being, users are advised to migrate their config files to use
\(lqkrb5_server\(rq
instead\&.
.RE
.PP
krb5_realm (string)
.RS 4
Specify the Kerberos REALM (for SASL/GSSAPI auth)\&.
.sp
Default: System defaults, see
/etc/krb5\&.conf
.RE
.PP
krb5_canonicalize (boolean)
.RS 4
Specifies if the host principal should be canonicalized when connecting to LDAP server\&. This feature is available with MIT Kerberos >= 1\&.7
.sp
Default: false
.RE
.PP
krb5_use_kdcinfo (boolean)
.RS 4
Specifies if the SSSD should instruct the Kerberos libraries what realm and which KDCs to use\&. This option is on by default, if you disable it, you need to configure the Kerberos library using the
\fBkrb5.conf\fR(5)
configuration file\&.
.sp
See the
\fBsssd_krb5_locator_plugin\fR(8)
manual page for more information on the locator plugin\&.
.sp
Default: true
.RE
.PP
ldap_pwd_policy (string)
.RS 4
Select the policy to evaluate the password expiration on the client side\&. The following values are allowed:
.sp
\fInone\fR
\- No evaluation on the client side\&. This option cannot disable server\-side password policies\&.
.sp
\fIshadow\fR
\- Use
\fBshadow\fR(5)
style attributes to evaluate if the password has expired\&.
.sp
\fImit_kerberos\fR
\- Use the attributes used by MIT Kerberos to determine if the password has expired\&. Use chpass_provider=krb5 to update these attributes when the password is changed\&.
.sp
Default: none
.sp
\fINote\fR: if a password policy is configured on server side, it always takes precedence over policy set with this option\&.
.RE
.PP
ldap_referrals (boolean)
.RS 4
Specifies whether automatic referral chasing should be enabled\&.
.sp
Please note that sssd only supports referral chasing when it is compiled with OpenLDAP version 2\&.4\&.13 or higher\&.
.sp
Chasing referrals may incur a performance penalty in environments that use them heavily, a notable example is Microsoft Active Directory\&. If your setup does not in fact require the use of referrals, setting this option to false might bring a noticeable performance improvement\&.
.sp
Default: true
.RE
.PP
ldap_dns_service_name (string)
.RS 4
Specifies the service name to use when service discovery is enabled\&.
.sp
Default: ldap
.RE
.PP
ldap_chpass_dns_service_name (string)
.RS 4
Specifies the service name to use to find an LDAP server which allows password changes when service discovery is enabled\&.
.sp
Default: not set, i\&.e\&. service discovery is disabled
.RE
.PP
ldap_chpass_update_last_change (bool)
.RS 4
Specifies whether to update the ldap_user_shadow_last_change attribute with days since the Epoch after a password change operation\&.
.sp
Default: False
.RE
.PP
ldap_access_filter (string)
.RS 4
If using access_provider = ldap and ldap_access_order = filter (default), this option is mandatory\&. It specifies an LDAP search filter criteria that must be met for the user to be granted access on this host\&. If access_provider = ldap, ldap_access_order = filter and this option is not set, it will result in all users being denied access\&. Use access_provider = permit to change this default behavior\&. Please note that this filter is applied on the LDAP user entry only\&.
.sp
Example:
.sp
.if n \{\
.RS 4
.\}
.nf
access_provider = ldap
ldap_access_filter = (employeeType=admin)
                        
.fi
.if n \{\
.RE
.\}
.sp
This example means that access to this host is restricted to users whose employeeType attribute is set to "admin"\&.
.sp
Offline caching for this feature is limited to determining whether the user\*(Aqs last online login was granted access permission\&. If they were granted access during their last login, they will continue to be granted access while offline and vice\-versa\&.
.sp
Default: Empty
.RE
.PP
ldap_account_expire_policy (string)
.RS 4
With this option a client side evaluation of access control attributes can be enabled\&.
.sp
Please note that it is always recommended to use server side access control, i\&.e\&. the LDAP server should deny the bind request with a suitable error code even if the password is correct\&.
.sp
The following values are allowed:
.sp
\fIshadow\fR: use the value of ldap_user_shadow_expire to determine if the account is expired\&.
.sp
\fIad\fR: use the value of the 32bit field ldap_user_ad_user_account_control and allow access if the second bit is not set\&. If the attribute is missing access is granted\&. Also the expiration time of the account is checked\&.
.sp
\fIrhds\fR,
\fIipa\fR,
\fI389ds\fR: use the value of ldap_ns_account_lock to check if access is allowed or not\&.
.sp
\fInds\fR: the values of ldap_user_nds_login_allowed_time_map, ldap_user_nds_login_disabled and ldap_user_nds_login_expiration_time are used to check if access is allowed\&. If both attributes are missing access is granted\&.
\fI This is an experimental feature, please use http://fedorahosted\&.org/sssd to report any issues\&. \fR
.sp
Please note that the ldap_access_order configuration option
\fImust\fR
include
\(lqexpire\(rq
in order for the ldap_account_expire_policy option to work\&.
.sp
Default: Empty
.RE
.PP
ldap_access_order (string)
.RS 4
Comma separated list of access control options\&. Allowed values are:
.sp
\fIfilter\fR: use ldap_access_filter
.sp
\fIlockout\fR: use account locking\&. If set, this option denies access in case that ldap attribute \*(AqpwdAccountLockedTime\*(Aq is present and has value of \*(Aq000001010000Z\*(Aq\&. Please see the option ldap_pwdlockout_dn\&.
.sp
\fIexpire\fR: use ldap_account_expire_policy
.sp
\fIauthorized_service\fR: use the authorizedService attribute to determine access
.sp
\fIhost\fR: use the host attribute to determine access
.sp
Default: filter
.sp
Please note that it is a configuration error if a value is used more than once\&.
.RE
.PP
ldap_pwdlockout_dn (string)
.RS 4
This option specifies the DN of password policy entry on LDAP server\&. Please note that absence of this option in sssd\&.conf in case of enabled account lockout checking will yield access denied as ppolicy attributes on LDAP server cannot be checked properly\&.
.sp
Example: cn=ppolicy,ou=policies,dc=example,dc=com
.sp
Default: cn=ppolicy,ou=policies,$ldap_search_base
.RE
.PP
ldap_deref (string)
.RS 4
Specifies how alias dereferencing is done when performing a search\&. The following options are allowed:
.sp
\fInever\fR: Aliases are never dereferenced\&.
.sp
\fIsearching\fR: Aliases are dereferenced in subordinates of the base object, but not in locating the base object of the search\&.
.sp
\fIfinding\fR: Aliases are only dereferenced when locating the base object of the search\&.
.sp
\fIalways\fR: Aliases are dereferenced both in searching and in locating the base object of the search\&.
.sp
Default: Empty (this is handled as
\fInever\fR
by the LDAP client libraries)
.RE
.PP
ldap_rfc2307_fallback_to_local_users (boolean)
.RS 4
Allows to retain local users as members of an LDAP group for servers that use the RFC2307 schema\&.
.sp
In some environments where the RFC2307 schema is used, local users are made members of LDAP groups by adding their names to the memberUid attribute\&. The self\-consistency of the domain is compromised when this is done, so SSSD would normally remove the "missing" users from the cached group memberships as soon as nsswitch tries to fetch information about the user via getpw*() or initgroups() calls\&.
.sp
This option falls back to checking if local users are referenced, and caches them so that later initgroups() calls will augment the local users with the additional LDAP groups\&.
.sp
Default: false
.RE
.SH "SUDO OPTIONS"
.PP
The detailed instructions for configuration of sudo_provider are in the manual page
\fBsssd-sudo\fR(5)\&.
.PP
.PP
ldap_sudorule_object_class (string)
.RS 4
The object class of a sudo rule entry in LDAP\&.
.sp
Default: sudoRole
.RE
.PP
ldap_sudorule_name (string)
.RS 4
The LDAP attribute that corresponds to the sudo rule name\&.
.sp
Default: cn
.RE
.PP
ldap_sudorule_command (string)
.RS 4
The LDAP attribute that corresponds to the command name\&.
.sp
Default: sudoCommand
.RE
.PP
ldap_sudorule_host (string)
.RS 4
The LDAP attribute that corresponds to the host name (or host IP address, host IP network, or host netgroup)
.sp
Default: sudoHost
.RE
.PP
ldap_sudorule_user (string)
.RS 4
The LDAP attribute that corresponds to the user name (or UID, group name or user\*(Aqs netgroup)
.sp
Default: sudoUser
.RE
.PP
ldap_sudorule_option (string)
.RS 4
The LDAP attribute that corresponds to the sudo options\&.
.sp
Default: sudoOption
.RE
.PP
ldap_sudorule_runasuser (string)
.RS 4
The LDAP attribute that corresponds to the user name that commands may be run as\&.
.sp
Default: sudoRunAsUser
.RE
.PP
ldap_sudorule_runasgroup (string)
.RS 4
The LDAP attribute that corresponds to the group name or group GID that commands may be run as\&.
.sp
Default: sudoRunAsGroup
.RE
.PP
ldap_sudorule_notbefore (string)
.RS 4
The LDAP attribute that corresponds to the start date/time for when the sudo rule is valid\&.
.sp
Default: sudoNotBefore
.RE
.PP
ldap_sudorule_notafter (string)
.RS 4
The LDAP attribute that corresponds to the expiration date/time, after which the sudo rule will no longer be valid\&.
.sp
Default: sudoNotAfter
.RE
.PP
ldap_sudorule_order (string)
.RS 4
The LDAP attribute that corresponds to the ordering index of the rule\&.
.sp
Default: sudoOrder
.RE
.PP
ldap_sudo_full_refresh_interval (integer)
.RS 4
How many seconds SSSD will wait between executing a full refresh of sudo rules (which downloads all rules that are stored on the server)\&.
.sp
The value must be greater than
\fIldap_sudo_smart_refresh_interval \fR
.sp
Default: 21600 (6 hours)
.RE
.PP
ldap_sudo_smart_refresh_interval (integer)
.RS 4
How many seconds SSSD has to wait before executing a smart refresh of sudo rules (which downloads all rules that have USN higher than the highest USN of cached rules)\&.
.sp
If USN attributes are not supported by the server, the modifyTimestamp attribute is used instead\&.
.sp
Default: 900 (15 minutes)
.RE
.PP
ldap_sudo_use_host_filter (boolean)
.RS 4
If true, SSSD will download only rules that are applicable to this machine (using the IPv4 or IPv6 host/network addresses and hostnames)\&.
.sp
Default: true
.RE
.PP
ldap_sudo_hostnames (string)
.RS 4
Space separated list of hostnames or fully qualified domain names that should be used to filter the rules\&.
.sp
If this option is empty, SSSD will try to discover the hostname and the fully qualified domain name automatically\&.
.sp
If
\fIldap_sudo_use_host_filter\fR
is
\fIfalse\fR
then this option has no effect\&.
.sp
Default: not specified
.RE
.PP
ldap_sudo_ip (string)
.RS 4
Space separated list of IPv4 or IPv6 host/network addresses that should be used to filter the rules\&.
.sp
If this option is empty, SSSD will try to discover the addresses automatically\&.
.sp
If
\fIldap_sudo_use_host_filter\fR
is
\fIfalse\fR
then this option has no effect\&.
.sp
Default: not specified
.RE
.PP
ldap_sudo_include_netgroups (boolean)
.RS 4
If true then SSSD will download every rule that contains a netgroup in sudoHost attribute\&.
.sp
If
\fIldap_sudo_use_host_filter\fR
is
\fIfalse\fR
then this option has no effect\&.
.sp
Default: true
.RE
.PP
ldap_sudo_include_regexp (boolean)
.RS 4
If true then SSSD will download every rule that contains a wildcard in sudoHost attribute\&.
.sp
If
\fIldap_sudo_use_host_filter\fR
is
\fIfalse\fR
then this option has no effect\&.
.sp
Default: true
.RE
.PP
This manual page only describes attribute name mapping\&. For detailed explanation of sudo related attribute semantics, see
\fBsudoers.ldap\fR(5)
.SH "AUTOFS OPTIONS"
.PP
Please note that the default values correspond to the default schema which is RFC2307\&.
.PP
.PP
ldap_autofs_map_object_class (string)
.RS 4
The object class of an automount map entry in LDAP\&.
.sp
Default: automountMap
.RE
.PP
ldap_autofs_map_name (string)
.RS 4
The name of an automount map entry in LDAP\&.
.sp
Default: ou
.RE
.PP
ldap_autofs_entry_object_class (string)
.RS 4
The object class of an automount map entry in LDAP\&.
.sp
Default: automountMap
.RE
.PP
ldap_autofs_entry_key (string)
.RS 4
The key of an automount entry in LDAP\&. The entry usually corresponds to a mount point\&.
.sp
Default: cn
.RE
.PP
ldap_autofs_entry_value (string)
.RS 4
The key of an automount entry in LDAP\&. The entry usually corresponds to a mount point\&.
.sp
Default: automountInformation
.RE
.PP
Please note that the automounter only reads the master map on startup, so if any autofs\-related changes are made to the sssd\&.conf, you typically also need to restart the automounter daemon after restarting the SSSD\&.
.SH "ADVANCED OPTIONS"
.PP
These options are supported by LDAP domains, but they should be used with caution\&. Please include them in your configuration only if you know what you are doing\&.
.PP
ldap_netgroup_search_base (string)
.RS 4
An optional base DN, search scope and LDAP filter to restrict LDAP searches for this attribute type\&.
.sp
syntax:
.sp
.if n \{\
.RS 4
.\}
.nf
search_base[?scope?[filter][?search_base?scope?[filter]]*]
.fi
.if n \{\
.RE
.\}
.sp
The scope can be one of "base", "onelevel" or "subtree"\&. The filter must be a valid LDAP search filter as specified by http://www\&.ietf\&.org/rfc/rfc2254\&.txt
.sp
For examples of this syntax, please refer to the
\(lqldap_search_base\(rq
examples section\&.
.sp
Default: the value of
\fIldap_search_base\fR
.sp
Please note that specifying scope or filter is not supported for searches against an Active Directory Server that might yield a large number of results and trigger the Range Retrieval extension in the response\&.
.RE
.PP
ldap_user_search_base (string)
.RS 4
An optional base DN, search scope and LDAP filter to restrict LDAP searches for this attribute type\&.
.sp
syntax:
.sp
.if n \{\
.RS 4
.\}
.nf
search_base[?scope?[filter][?search_base?scope?[filter]]*]
.fi
.if n \{\
.RE
.\}
.sp
The scope can be one of "base", "onelevel" or "subtree"\&. The filter must be a valid LDAP search filter as specified by http://www\&.ietf\&.org/rfc/rfc2254\&.txt
.sp
For examples of this syntax, please refer to the
\(lqldap_search_base\(rq
examples section\&.
.sp
Default: the value of
\fIldap_search_base\fR
.sp
Please note that specifying scope or filter is not supported for searches against an Active Directory Server that might yield a large number of results and trigger the Range Retrieval extension in the response\&.
.RE
.PP
ldap_group_search_base (string)
.RS 4
An optional base DN, search scope and LDAP filter to restrict LDAP searches for this attribute type\&.
.sp
syntax:
.sp
.if n \{\
.RS 4
.\}
.nf
search_base[?scope?[filter][?search_base?scope?[filter]]*]
.fi
.if n \{\
.RE
.\}
.sp
The scope can be one of "base", "onelevel" or "subtree"\&. The filter must be a valid LDAP search filter as specified by http://www\&.ietf\&.org/rfc/rfc2254\&.txt
.sp
For examples of this syntax, please refer to the
\(lqldap_search_base\(rq
examples section\&.
.sp
Default: the value of
\fIldap_search_base\fR
.sp
Please note that specifying scope or filter is not supported for searches against an Active Directory Server that might yield a large number of results and trigger the Range Retrieval extension in the response\&.
.RE
.PP
ldap_user_search_filter (string)
.RS 4
This option specifies an additional LDAP search filter criteria that restrict user searches\&.
.sp
This option is
\fIdeprecated\fR
in favor of the syntax used by ldap_user_search_base\&.
.sp
Default: not set
.sp
Example:
.sp
.if n \{\
.RS 4
.\}
.nf
                            ldap_user_search_filter = (loginShell=/bin/tcsh)
                        
.fi
.if n \{\
.RE
.\}
.sp
This filter would restrict user searches to users that have their shell set to /bin/tcsh\&.
.RE
.PP
ldap_group_search_filter (string)
.RS 4
This option specifies an additional LDAP search filter criteria that restrict group searches\&.
.sp
This option is
\fIdeprecated\fR
in favor of the syntax used by ldap_group_search_base\&.
.sp
Default: not set
.RE
.PP
ldap_sudo_search_base (string)
.RS 4
An optional base DN, search scope and LDAP filter to restrict LDAP searches for this attribute type\&.
.sp
syntax:
.sp
.if n \{\
.RS 4
.\}
.nf
search_base[?scope?[filter][?search_base?scope?[filter]]*]
.fi
.if n \{\
.RE
.\}
.sp
The scope can be one of "base", "onelevel" or "subtree"\&. The filter must be a valid LDAP search filter as specified by http://www\&.ietf\&.org/rfc/rfc2254\&.txt
.sp
For examples of this syntax, please refer to the
\(lqldap_search_base\(rq
examples section\&.
.sp
Default: the value of
\fIldap_search_base\fR
.sp
Please note that specifying scope or filter is not supported for searches against an Active Directory Server that might yield a large number of results and trigger the Range Retrieval extension in the response\&.
.RE
.PP
ldap_autofs_search_base (string)
.RS 4
An optional base DN, search scope and LDAP filter to restrict LDAP searches for this attribute type\&.
.sp
syntax:
.sp
.if n \{\
.RS 4
.\}
.nf
search_base[?scope?[filter][?search_base?scope?[filter]]*]
.fi
.if n \{\
.RE
.\}
.sp
The scope can be one of "base", "onelevel" or "subtree"\&. The filter must be a valid LDAP search filter as specified by http://www\&.ietf\&.org/rfc/rfc2254\&.txt
.sp
For examples of this syntax, please refer to the
\(lqldap_search_base\(rq
examples section\&.
.sp
Default: the value of
\fIldap_search_base\fR
.sp
Please note that specifying scope or filter is not supported for searches against an Active Directory Server that might yield a large number of results and trigger the Range Retrieval extension in the response\&.
.RE
.SH "FAILOVER"
.PP
The failover feature allows back ends to automatically switch to a different server if the current server fails\&.
.SS "Failover Syntax"
.PP
The list of servers is given as a comma\-separated list; any number of spaces is allowed around the comma\&. The servers are listed in order of preference\&. The list can contain any number of servers\&.
.PP
For each failover\-enabled config option, two variants exist:
\fIprimary\fR
and
\fIbackup\fR\&. The idea is that servers in the primary list are preferred and backup servers are only searched if no primary servers can be reached\&. If a backup server is selected, a timeout of 31 seconds is set\&. After this timeout SSSD will periodically try to reconnect to one of the primary servers\&. If it succeeds, it will replace the current active (backup) server\&.
.SS "The Failover Mechanism"
.PP
The failover mechanism distinguishes between a machine and a service\&. The back end first tries to resolve the hostname of a given machine; if this resolution attempt fails, the machine is considered offline\&. No further attempts are made to connect to this machine for any other service\&. If the resolution attempt succeeds, the back end tries to connect to a service on this machine\&. If the service connection attempt fails, then only this particular service is considered offline and the back end automatically switches over to the next service\&. The machine is still considered online and might still be tried for another service\&.
.PP
Further connection attempts are made to machines or services marked as offline after a specified period of time; this is currently hard coded to 30 seconds\&.
.PP
If there are no more machines to try, the back end as a whole switches to offline mode, and then attempts to reconnect every 30 seconds\&.
.SH "SERVICE DISCOVERY"
.PP
The service discovery feature allows back ends to automatically find the appropriate servers to connect to using a special DNS query\&. This feature is not supported for backup servers\&.
.SS "Configuration"
.PP
If no servers are specified, the back end automatically uses service discovery to try to find a server\&. Optionally, the user may choose to use both fixed server addresses and service discovery by inserting a special keyword,
\(lq_srv_\(rq, in the list of servers\&. The order of preference is maintained\&. This feature is useful if, for example, the user prefers to use service discovery whenever possible, and fall back to a specific server when no servers can be discovered using DNS\&.
.SS "The domain name"
.PP
Please refer to the
\(lqdns_discovery_domain\(rq
parameter in the
\fBsssd.conf\fR(5)
manual page for more details\&.
.SS "The protocol"
.PP
The queries usually specify _tcp as the protocol\&. Exceptions are documented in respective option description\&.
.SS "See Also"
.PP
For more information on the service discovery mechanism, refer to RFC 2782\&.
.SH "ID MAPPING"
.PP
The ID\-mapping feature allows SSSD to act as a client of Active Directory without requiring administrators to extend user attributes to support POSIX attributes for user and group identifiers\&.
.PP
NOTE: When ID\-mapping is enabled, the uidNumber and gidNumber attributes are ignored\&. This is to avoid the possibility of conflicts between automatically\-assigned and manually\-assigned values\&. If you need to use manually\-assigned values, ALL values must be manually\-assigned\&.
.PP
Please note that changing the ID mapping related configuration options will cause user and group IDs to change\&. At the moment, SSSD does not support changing IDs, so the SSSD database must be removed\&. Because cached passwords are also stored in the database, removing the database should only be performed while the authentication servers are reachable, otherwise users might get locked out\&. In order to cache the password, an authentication must be performed\&. It is not sufficient to use
\fBsss_cache\fR(8)
to remove the database, rather the process consists of:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Making sure the remote servers are reachable
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Stopping the SSSD service
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Removing the database
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Starting the SSSD service
.RE
.sp
Moreover, as the change of IDs might necessitate the adjustment of other system properties such as file and directory ownership, it\*(Aqs advisable to plan ahead and test the ID mapping configuration thoroughly\&.
.SS "Mapping Algorithm"
.PP
Active Directory provides an objectSID for every user and group object in the directory\&. This objectSID can be broken up into components that represent the Active Directory domain identity and the relative identifier (RID) of the user or group object\&.
.PP
The SSSD ID\-mapping algorithm takes a range of available UIDs and divides it into equally\-sized component sections \- called "slices"\-\&. Each slice represents the space available to an Active Directory domain\&.
.PP
When a user or group entry for a particular domain is encountered for the first time, the SSSD allocates one of the available slices for that domain\&. In order to make this slice\-assignment repeatable on different client machines, we select the slice based on the following algorithm:
.PP
The SID string is passed through the murmurhash3 algorithm to convert it to a 32\-bit hashed value\&. We then take the modulus of this value with the total number of available slices to pick the slice\&.
.PP
NOTE: It is possible to encounter collisions in the hash and subsequent modulus\&. In these situations, we will select the next available slice, but it may not be possible to reproduce the same exact set of slices on other machines (since the order that they are encountered will determine their slice)\&. In this situation, it is recommended to either switch to using explicit POSIX attributes in Active Directory (disabling ID\-mapping) or configure a default domain to guarantee that at least one is always consistent\&. See
\(lqConfiguration\(rq
for details\&.
.SS "Configuration"
.PP
Minimum configuration (in the
\(lq[domain/DOMAINNAME]\(rq
section):
.PP
.if n \{\
.RS 4
.\}
.nf
ldap_id_mapping = True
ldap_schema = ad
.fi
.if n \{\
.RE
.\}
.PP
The default configuration results in configuring 10,000 slices, each capable of holding up to 200,000 IDs, starting from 10,001 and going up to 2,000,100,000\&. This should be sufficient for most deployments\&.
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBAdvanced Configuration\fR
.RS 4
.PP
ldap_idmap_range_min (integer)
.RS 4
Specifies the lower bound of the range of POSIX IDs to use for mapping Active Directory user and group SIDs\&.
.sp
NOTE: This option is different from
\(lqmin_id\(rq
in that
\(lqmin_id\(rq
acts to filter the output of requests to this domain, whereas this option controls the range of ID assignment\&. This is a subtle distinction, but the good general advice would be to have
\(lqmin_id\(rq
be less\-than or equal to
\(lqldap_idmap_range_min\(rq
.sp
Default: 200000
.RE
.PP
ldap_idmap_range_max (integer)
.RS 4
Specifies the upper bound of the range of POSIX IDs to use for mapping Active Directory user and group SIDs\&.
.sp
NOTE: This option is different from
\(lqmax_id\(rq
in that
\(lqmax_id\(rq
acts to filter the output of requests to this domain, whereas this option controls the range of ID assignment\&. This is a subtle distinction, but the good general advice would be to have
\(lqmax_id\(rq
be greater\-than or equal to
\(lqldap_idmap_range_max\(rq
.sp
Default: 2000200000
.RE
.PP
ldap_idmap_range_size (integer)
.RS 4
Specifies the number of IDs available for each slice\&. If the range size does not divide evenly into the min and max values, it will create as many complete slices as it can\&.
.sp
Default: 200000
.RE
.PP
ldap_idmap_default_domain_sid (string)
.RS 4
Specify the domain SID of the default domain\&. This will guarantee that this domain will always be assigned to slice zero in the ID map, bypassing the murmurhash algorithm described above\&.
.sp
Default: not set
.RE
.PP
ldap_idmap_default_domain (string)
.RS 4
Specify the name of the default domain\&.
.sp
Default: not set
.RE
.PP
ldap_idmap_autorid_compat (boolean)
.RS 4
Changes the behavior of the ID\-mapping algorithm to behave more similarly to winbind\*(Aqs
\(lqidmap_autorid\(rq
algorithm\&.
.sp
When this option is configured, domains will be allocated starting with slice zero and increasing monatomically with each additional domain\&.
.sp
NOTE: This algorithm is non\-deterministic (it depends on the order that users and groups are requested)\&. If this mode is required for compatibility with machines running winbind, it is recommended to also use the
\(lqldap_idmap_default_domain_sid\(rq
option to guarantee that at least one domain is consistently allocated to slice zero\&.
.sp
Default: False
.RE
.RE
.SH "EXAMPLE"
.PP
The following example assumes that SSSD is correctly configured and LDAP is set to one of the domains in the
\fI[domains]\fR
section\&.
.PP
.if n \{\
.RS 4
.\}
.nf
    [domain/LDAP]
    id_provider = ldap
    auth_provider = ldap
    ldap_uri = ldap://ldap\&.mydomain\&.org
    ldap_search_base = dc=mydomain,dc=org
    ldap_tls_reqcert = demand
    cache_credentials = true
.fi
.if n \{\
.RE
.\}
.sp
.SH "NOTES"
.PP
The descriptions of some of the configuration options in this manual page are based on the
\fBldap.conf\fR(5)
manual page from the OpenLDAP 2\&.4 distribution\&.
.SH "SEE ALSO"
.PP
\fBsssd\fR(8),
\fBsssd.conf\fR(5),
\fBsssd-ldap\fR(5),
\fBsssd-krb5\fR(5),
\fBsssd-simple\fR(5),
\fBsssd-ipa\fR(5),
\fBsssd-ad\fR(5),
\fBsssd-sudo\fR(5),\fBsss_cache\fR(8),
\fBsss_debuglevel\fR(8),
\fBsss_groupadd\fR(8),
\fBsss_groupdel\fR(8),
\fBsss_groupshow\fR(8),
\fBsss_groupmod\fR(8),
\fBsss_useradd\fR(8),
\fBsss_userdel\fR(8),
\fBsss_usermod\fR(8),
\fBsss_obfuscate\fR(8),
\fBsss_seed\fR(8),
\fBsssd_krb5_locator_plugin\fR(8),
\fBsss_ssh_authorizedkeys\fR(8), \fBsss_ssh_knownhostsproxy\fR(8),\fBsssd-ifp\fR(5),\fBpam_sss\fR(8)\&.
.SH "AUTHORS"
.PP
\fBThe SSSD upstream \- http://fedorahosted\&.org/sssd\fR
.SH "NOTES"
.IP " 1." 4
MSDN(TM) documentation
.RS 4
\%http://msdn.microsoft.com/en-us/library/windows/desktop/aa746475%28v=vs.85%29.aspx
.RE
