#! /bin/sh -e

invoke_failure() {
    # invoke-rc.d failed
    return
}

# Automatically added by dh_installinit
if [ -x "/etc/init.d/sssd" ]; then
	invoke-rc.d sssd stop || invoke_failure
fi
# End automatically added section


